### ISSUE TITLE
``npm install datum-sdk`` raises an error

### ISSUE THREAD

**Issue by srisankethu** [Datum/datum-sdk#2]
I am trying to build an app for a [contest](https://gitcoin.co/issue/Datum/Datum-Gitcoin-Bounty/1/915). As I run the installation command, I get the error of "unable to connect to github.com". I use a proxy. Please help!

**Comment by ducatimo** [comment]
Think the problem is related to your network configuration and proxy usage.

Can you please check following points:
- Do you have the same problem for other npm packages too ?
- Which version of npm is installed ?

You can try to adapt git configuration like that to use https:// instead of git://
```
git config --global url."https://".insteadOf git://
```

Configuration changed related to this issue with same problem
https://github.com/angular/angular-phonecat/issues/235

**Comment by srisankethu** [comment]
@ducatimo Thanks a lot. It works!
